"""add_skip_next_reanalyze_to_cards

Revision ID: 211b84143ca6
Revises: 60b34c9aa164
Create Date: 2026-03-05 20:09:22.220185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '211b84143ca6'
down_revision: Union[str, None] = '60b34c9aa164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('skip_next_reanalyze', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'skip_next_reanalyze')
    # ### end Alembic commands ###
