"""add_product_dna_to_cards

Revision ID: 60b34c9aa164
Revises: 009_profile_avatar_access
Create Date: 2026-03-04 20:00:06.894589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60b34c9aa164'
down_revision: Union[str, None] = '009_profile_avatar_access'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_card_approvals_id'), 'card_approvals', ['id'], unique=False)
    op.add_column('cards', sa.Column('product_dna', sa.Text(), nullable=True))
    op.create_index(op.f('ix_fixed_file_entries_id'), 'fixed_file_entries', ['id'], unique=False)
    op.create_index(op.f('ix_registration_access_requests_id'), 'registration_access_requests', ['id'], unique=False)
    op.alter_column('user_invites', 'is_used',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user_invites', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('user_invites_token_key', 'user_invites', type_='unique')
    op.drop_index('ix_user_invites_token', table_name='user_invites')
    op.create_index(op.f('ix_user_invites_token'), 'user_invites', ['token'], unique=True)
    op.create_index(op.f('ix_user_invites_id'), 'user_invites', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_invites_id'), table_name='user_invites')
    op.drop_index(op.f('ix_user_invites_token'), table_name='user_invites')
    op.create_index('ix_user_invites_token', 'user_invites', ['token'], unique=False)
    op.create_unique_constraint('user_invites_token_key', 'user_invites', ['token'])
    op.alter_column('user_invites', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_invites', 'is_used',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_registration_access_requests_id'), table_name='registration_access_requests')
    op.drop_index(op.f('ix_fixed_file_entries_id'), table_name='fixed_file_entries')
    op.drop_column('cards', 'product_dna')
    op.drop_index(op.f('ix_card_approvals_id'), table_name='card_approvals')
    # ### end Alembic commands ###
