"""add_photo_studio_and_promotion

Revision ID: adb6bc5d6680
Revises: 002
Create Date: 2026-02-24 19:58:06.529946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adb6bc5d6680'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_session_id', sa.String(length=128), nullable=False),
    sa.Column('last_generated_relpath', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_chat_sessions_client_session_id'), 'photo_chat_sessions', ['client_session_id'], unique=False)
    op.create_index(op.f('ix_photo_chat_sessions_id'), 'photo_chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_photo_chat_sessions_user_id'), 'photo_chat_sessions', ['user_id'], unique=False)
    op.create_table('photo_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_type', sa.Enum('MODEL', 'SCENE', 'POSE', 'CUSTOM', name='assettype'), nullable=False),
    sa.Column('owner_type', sa.Enum('SYSTEM', 'USER', name='assetownertype'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_assets_asset_type'), 'photo_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_photo_assets_category'), 'photo_assets', ['category'], unique=False)
    op.create_index(op.f('ix_photo_assets_owner_type'), 'photo_assets', ['owner_type'], unique=False)
    op.create_index(op.f('ix_photo_assets_user_id'), 'photo_assets', ['user_id'], unique=False)
    op.create_table('photo_chat_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('relpath', sa.String(length=512), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['photo_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_chat_media_id'), 'photo_chat_media', ['id'], unique=False)
    op.create_index(op.f('ix_photo_chat_media_session_id'), 'photo_chat_media', ['session_id'], unique=False)
    op.create_table('photo_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('msg_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['photo_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_chat_messages_id'), 'photo_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_photo_chat_messages_session_id'), 'photo_chat_messages', ['session_id'], unique=False)
    op.create_table('promotion_companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wb_company_id', sa.BigInteger(), nullable=False),
    sa.Column('nm_id', sa.BigInteger(), nullable=False),
    sa.Column('card_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('title_changed', sa.Boolean(), nullable=False),
    sa.Column('from_main', sa.Boolean(), nullable=False),
    sa.Column('max_slots', sa.Integer(), nullable=False),
    sa.Column('photos_count', sa.Integer(), nullable=False),
    sa.Column('views_per_photo', sa.Integer(), nullable=False),
    sa.Column('cpm', sa.Integer(), nullable=False),
    sa.Column('spend_rub', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'RUNNING', 'FINISHED', 'FAILED', 'STOPPED', name='promotionstatus'), nullable=False),
    sa.Column('last_total_shows', sa.Integer(), nullable=False),
    sa.Column('last_total_clicks', sa.Integer(), nullable=False),
    sa.Column('current_photo_order', sa.Integer(), nullable=False),
    sa.Column('winner_photo_order', sa.Integer(), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('keep_winner_as_main', sa.Boolean(), nullable=False),
    sa.Column('original_media_json', sa.String(length=8000), nullable=True),
    sa.Column('current_uploaded_wb_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_companies_card_id'), 'promotion_companies', ['card_id'], unique=False)
    op.create_index(op.f('ix_promotion_companies_nm_id'), 'promotion_companies', ['nm_id'], unique=False)
    op.create_index(op.f('ix_promotion_companies_status'), 'promotion_companies', ['status'], unique=False)
    op.create_index(op.f('ix_promotion_companies_user_id'), 'promotion_companies', ['user_id'], unique=False)
    op.create_index(op.f('ix_promotion_companies_wb_company_id'), 'promotion_companies', ['wb_company_id'], unique=False)
    op.create_table('promotion_photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('wb_url', sa.String(length=1024), nullable=True),
    sa.Column('shows', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['promotion_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_photos_company_id'), 'promotion_photos', ['company_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_tasks_id'), 'analysis_tasks', ['id'], unique=False)
    op.alter_column('card_issues', 'status',
               existing_type=postgresql.ENUM('pending', 'fixed', 'skipped', 'postponed', 'auto_fixed', name='issuestatus'),
               nullable=False)
    op.create_index(op.f('ix_card_issues_id'), 'card_issues', ['id'], unique=False)
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.create_index(op.f('ix_cards_nm_id'), 'cards', ['nm_id'], unique=False)
    op.create_index('idx_issue_rules_category', 'issue_rules', ['category'], unique=False)
    op.create_index('idx_issue_rules_code', 'issue_rules', ['code'], unique=False)
    op.create_index('idx_issue_rules_severity', 'issue_rules', ['severity'], unique=False)
    op.create_index(op.f('ix_issue_rules_id'), 'issue_rules', ['id'], unique=False)
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    op.drop_index('idx_users_email', table_name='users')
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.create_index('idx_users_email', 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_index(op.f('ix_issue_rules_id'), table_name='issue_rules')
    op.drop_index('idx_issue_rules_severity', table_name='issue_rules')
    op.drop_index('idx_issue_rules_code', table_name='issue_rules')
    op.drop_index('idx_issue_rules_category', table_name='issue_rules')
    op.drop_index(op.f('ix_cards_nm_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_index(op.f('ix_card_issues_id'), table_name='card_issues')
    op.alter_column('card_issues', 'status',
               existing_type=postgresql.ENUM('pending', 'fixed', 'skipped', 'postponed', 'auto_fixed', name='issuestatus'),
               nullable=True)
    op.drop_index(op.f('ix_analysis_tasks_id'), table_name='analysis_tasks')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_promotion_photos_company_id'), table_name='promotion_photos')
    op.drop_table('promotion_photos')
    op.drop_index(op.f('ix_promotion_companies_wb_company_id'), table_name='promotion_companies')
    op.drop_index(op.f('ix_promotion_companies_user_id'), table_name='promotion_companies')
    op.drop_index(op.f('ix_promotion_companies_status'), table_name='promotion_companies')
    op.drop_index(op.f('ix_promotion_companies_nm_id'), table_name='promotion_companies')
    op.drop_index(op.f('ix_promotion_companies_card_id'), table_name='promotion_companies')
    op.drop_table('promotion_companies')
    op.drop_index(op.f('ix_photo_chat_messages_session_id'), table_name='photo_chat_messages')
    op.drop_index(op.f('ix_photo_chat_messages_id'), table_name='photo_chat_messages')
    op.drop_table('photo_chat_messages')
    op.drop_index(op.f('ix_photo_chat_media_session_id'), table_name='photo_chat_media')
    op.drop_index(op.f('ix_photo_chat_media_id'), table_name='photo_chat_media')
    op.drop_table('photo_chat_media')
    op.drop_index(op.f('ix_photo_assets_user_id'), table_name='photo_assets')
    op.drop_index(op.f('ix_photo_assets_owner_type'), table_name='photo_assets')
    op.drop_index(op.f('ix_photo_assets_category'), table_name='photo_assets')
    op.drop_index(op.f('ix_photo_assets_asset_type'), table_name='photo_assets')
    op.drop_table('photo_assets')
    op.drop_index(op.f('ix_photo_chat_sessions_user_id'), table_name='photo_chat_sessions')
    op.drop_index(op.f('ix_photo_chat_sessions_id'), table_name='photo_chat_sessions')
    op.drop_index(op.f('ix_photo_chat_sessions_client_session_id'), table_name='photo_chat_sessions')
    op.drop_table('photo_chat_sessions')
    # ### end Alembic commands ###
